### PR TITLE
storage percentages

### PR DESCRIPTION
**Pull request by woodbe**
To resolve biometricITC/cPP-toolboxes#58

### CODE REVIEW

**Review by n-kai — CHANGES_REQUESTED** [review]
L101 should be changed to 
[cols=".^2,.^3,.^3",options="header",]

**Comment by gregott** [comment]
I do not see why the bottle or tube could not be reused indefinitely.  Isn't it just a platform to hold the printed paper to give it shape?  If the paper can be removed from the bottle or tube, the bottle or tube should last forever.  If we are assuming it is always combined (glued) with the paper then I am OK with the table as is.

**Comment by n-kai** [comment]
@gregott, I agree with you and I created PR #16 to fix this issue. Wax can also be reused.

**Review by n-kai — CHANGES_REQUESTED** [review]
Please apply PR #16 to your branch.

**Review by n-kai — APPROVED** [review]

**Review by gregott — APPROVED** [review]

**Pull request merged**
